name: your_env_name
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - ipython
  - mamba
  - pip
  - pip:
      - torch
      - torchvision
      - torchaudio
      - tensorflow
      - opencv-python
      - tqdm
      - requests
      - pydicom
      - scikit-image
      - wandb
      - pytorch3d